# Generated by Django 4.2.6 on 2023-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.TextField(max_length=100),
        ),
    ]
